const Map<String, dynamic> allSubjects = {
  'ukrainian_lang_and_lit': 'Українська мова і література',
  'ukrainian_lang': 'Українська мова',
  'math': 'Математика',
  'nmt': 'НМТ',
  'ukraine_history': 'Історія України',
  'physics': 'Фізика',
  'chemistry': 'Хімія',
  'geography': 'Географія',
  'biology': 'Біологія',
  'english_lang': 'Англійська мова',
  'german_lang': 'Німецька мова',
  'french_lang': 'Французька мова',
  'spanish_lang': 'Іспанська мова',
  'zno_teachers': 'ЗНО для вчителів',
  'master': {
    'tznk': 'ТЗНК',
    'master_english_lang': 'Англійська мова в магістратуру',
    'master_german_lang': 'Німецька мова в магістратуру',
    'master_french_lang': 'Французька мова в магістратуру',
    'master_spanish_lang': 'Іспанська мова в магістратуру',
    'master_pravo': 'Право в магістратуру',
    'master_admin': 'Управління та адміністрування в магістратуру',
    'master_finance': 'Облік та фінанси в магістратуру',
    'master_psychology': 'Психологія та соціологія в магістратуру',
    'master_economics': 'Економіка та міжнародна економіка в магістратуру',
    'master_politics': 'Політологія та міжнародні відносини в магістратуру'
  },
};
